const { sendErrorMessage } = require("../../utils");

const MIN = 0;
const MAX = 199999;
const randNum = Math.floor(Math.random() * (MAX - MIN + 1)) + MIN;

const url = `https://www.thiswaifudoesnotexist.net/example-${randNum}.jpg`;

module.exports = {
  url,
  name: "waifu",
  description: "A random waifu picture (generated by AI)",
  execute(message, args) {
    if (url) {
      return message.channel.send(
        "Here is your random waifu (generated by AI)",
        {
          files: [url]
        }
      );
    }

    sendErrorMessage(message);
  }
};
